create table if not exists public.map_features (
  id text primary key,
  name text not null,
  status text not null check (status in ('existant', 'en cours', 'propose')),
  category text not null,
  layer_id text not null,
  layer_label text not null,
  layer_sort_order integer not null default 0,
  color text not null default '#1d4ed8',
  style jsonb null,
  geometry_type text not null check (geometry_type in ('point', 'line', 'polygon')),
  coordinates jsonb not null,
  sort_order integer not null default 0,
  source text not null default 'manual',
  deleted_at timestamptz null,
  deleted_by uuid null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.map_features
  add column if not exists layer_sort_order integer not null default 0;

alter table public.map_features
  add column if not exists deleted_at timestamptz null;

alter table public.map_features
  add column if not exists deleted_by uuid null;

alter table public.map_features
  add column if not exists style jsonb null;

create index if not exists idx_map_features_layer
  on public.map_features (layer_id, sort_order);

create index if not exists idx_map_features_category
  on public.map_features (category);

create index if not exists idx_map_features_source
  on public.map_features (source);

create index if not exists idx_map_features_deleted_at
  on public.map_features (deleted_at);

create index if not exists idx_map_features_category_layer_sort
  on public.map_features (category, layer_sort_order, layer_label);

do $$
declare
  has_non_zero_order boolean;
begin
  select exists (
    select 1
    from public.map_features
    where coalesce(layer_sort_order, 0) <> 0
  )
  into has_non_zero_order;

  if not has_non_zero_order then
    with ranked_layers as (
      select
        category,
        layer_id,
        row_number() over (
          partition by category
          order by min(layer_label), layer_id
        ) - 1 as computed_sort_order
      from public.map_features
      group by category, layer_id
    )
    update public.map_features as target
    set layer_sort_order = ranked_layers.computed_sort_order
    from ranked_layers
    where target.category = ranked_layers.category
      and target.layer_id = ranked_layers.layer_id;
  end if;
end;
$$;

create or replace function public.set_map_features_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_map_features_updated_at on public.map_features;
create trigger trg_map_features_updated_at
before update on public.map_features
for each row execute function public.set_map_features_updated_at();

alter table public.map_features enable row level security;

drop policy if exists "Public read map_features" on public.map_features;
create policy "Public read map_features"
on public.map_features
for select
using (deleted_at is null);

drop policy if exists "Authenticated write map_features" on public.map_features;
create policy "Authenticated write map_features"
on public.map_features
for all
to authenticated
using (true)
with check (true);

create table if not exists public.map_feature_versions (
  version_id bigint generated by default as identity primary key,
  feature_id text not null,
  operation text not null check (
    operation in ('insert', 'update', 'trash', 'restore', 'delete')
  ),
  snapshot jsonb not null,
  actor_id uuid null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_map_feature_versions_feature
  on public.map_feature_versions (feature_id, version_id desc);

create index if not exists idx_map_feature_versions_created_at
  on public.map_feature_versions (created_at desc);

create or replace function public.log_map_feature_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  current_operation text;
  payload jsonb;
  current_feature_id text;
begin
  if tg_op = 'INSERT' then
    current_operation := 'insert';
    payload := to_jsonb(new);
    current_feature_id := new.id;
  elsif tg_op = 'UPDATE' then
    if old.deleted_at is null and new.deleted_at is not null then
      current_operation := 'trash';
    elsif old.deleted_at is not null and new.deleted_at is null then
      current_operation := 'restore';
    else
      current_operation := 'update';
    end if;
    payload := to_jsonb(new);
    current_feature_id := new.id;
  else
    current_operation := 'delete';
    payload := to_jsonb(old);
    current_feature_id := old.id;
  end if;

  insert into public.map_feature_versions (feature_id, operation, snapshot, actor_id)
  values (current_feature_id, current_operation, payload, auth.uid());

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_map_features_versioning on public.map_features;
create trigger trg_map_features_versioning
after insert or update or delete on public.map_features
for each row execute function public.log_map_feature_version();

alter table public.map_feature_versions enable row level security;

drop policy if exists "Authenticated read map_feature_versions"
  on public.map_feature_versions;
create policy "Authenticated read map_feature_versions"
on public.map_feature_versions
for select
to authenticated
using (true);
